ALTER TABLE t_p57945357_law_ai_consultation.users
  ADD COLUMN IF NOT EXISTS subscription_consult_until TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS subscription_docs_until    TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL;
