ALTER TABLE t_p57945357_law_ai_consultation.legal_docs
  ADD COLUMN IF NOT EXISTS court_name VARCHAR(300) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS case_number VARCHAR(100) NOT NULL DEFAULT '';
