# ── Реэкспорт всего из старого prompts.py (обратная совместимость) ──────────
from .legacy import (
    TODAY,
    SYSTEM_CHAT, SYSTEM_CHAT_SIMPLE, SYSTEM_CHAT_DEEPSEEK,
    SYSTEM_DOC_GENERATE, SYSTEM_DOC_BY_TYPE,
    SYSTEM_FILE_ANALYZE_PROMPT, SYSTEM_FILE_QA_PROMPT,
    SYSTEM_BUSINESS_CHAT, SYSTEM_BUSINESS_CONTRACT,
    SYSTEM_COUNTERPARTY_CHECK, SYSTEM_TAX_ANALYSIS,
    SYSTEM_CASE_LAW, LEGAL_QUALITY_ADDON,
    REFUSAL_MARKERS, SIMPLE_QUERY_MARKERS, DOC_STARTERS,
)

from .block1_claims import BLOCK1_SYSTEM, BLOCK1_SUBTYPES
from .block2_petitions import BLOCK2_SYSTEM, BLOCK2_SUBTYPES
from .block3_appeals import BLOCK3_SYSTEM, BLOCK3_SUBTYPES
from .block4_responses import BLOCK4_SYSTEM, BLOCK4_SUBTYPES
from .block5_pretensions import BLOCK5_SYSTEM, BLOCK5_SUBTYPES
from .block6_contracts import BLOCK6_SYSTEM, BLOCK6_SUBTYPES
from .block7_corporate import BLOCK7_SYSTEM, BLOCK7_SUBTYPES
from .block8_labor import BLOCK8_SYSTEM, BLOCK8_SUBTYPES
from .block9_gov import BLOCK9_SYSTEM, BLOCK9_SUBTYPES
from .block10_criminal import BLOCK10_SYSTEM, BLOCK10_SUBTYPES
from .block11_website import BLOCK11_SYSTEM, BLOCK11_SUBTYPES
from .block12_special import BLOCK12_SYSTEM, BLOCK12_SUBTYPES
from .block13_decisions import BLOCK13_SYSTEM, BLOCK13_SUBTYPES
from .block14_speech import BLOCK14_SYSTEM, BLOCK14_SUBTYPES

# Единая таблица маппинга: doc_type → человекочитаемое название
ALL_SUBTYPES = {
    **BLOCK1_SUBTYPES, **BLOCK2_SUBTYPES, **BLOCK3_SUBTYPES,
    **BLOCK4_SUBTYPES, **BLOCK5_SUBTYPES, **BLOCK6_SUBTYPES,
    **BLOCK7_SUBTYPES, **BLOCK8_SUBTYPES, **BLOCK9_SUBTYPES,
    **BLOCK10_SUBTYPES, **BLOCK11_SUBTYPES, **BLOCK12_SUBTYPES,
    **BLOCK13_SUBTYPES, **BLOCK14_SUBTYPES,
}

# Маппинг: doc_type → системный промпт блока
BLOCK_BY_DOC_TYPE: dict[str, str] = {}
for _k in BLOCK1_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK1_SYSTEM
for _k in BLOCK2_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK2_SYSTEM
for _k in BLOCK3_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK3_SYSTEM
for _k in BLOCK4_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK4_SYSTEM
for _k in BLOCK5_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK5_SYSTEM
for _k in BLOCK6_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK6_SYSTEM
for _k in BLOCK7_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK7_SYSTEM
for _k in BLOCK8_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK8_SYSTEM
for _k in BLOCK9_SUBTYPES:  BLOCK_BY_DOC_TYPE[_k] = BLOCK9_SYSTEM
for _k in BLOCK10_SUBTYPES: BLOCK_BY_DOC_TYPE[_k] = BLOCK10_SYSTEM
for _k in BLOCK11_SUBTYPES: BLOCK_BY_DOC_TYPE[_k] = BLOCK11_SYSTEM
for _k in BLOCK12_SUBTYPES: BLOCK_BY_DOC_TYPE[_k] = BLOCK12_SYSTEM
for _k in BLOCK13_SUBTYPES: BLOCK_BY_DOC_TYPE[_k] = BLOCK13_SYSTEM
for _k in BLOCK14_SUBTYPES: BLOCK_BY_DOC_TYPE[_k] = BLOCK14_SYSTEM